#!/bin/bash

CWD=$(pwd)
PROGNAME=${BASH_SOURCE[0]}
[ $(basename -- $BASH_SOURCE) == $(basename -- $0) ] && EXIT="exit" || EXIT="return"

if [ "$(whoami)" = "root" ]; then
    echo "ERROR: do not use the BSP as root. Exiting..."
    ${EXIT}
fi

BBLAYERS_CONF=conf/bblayers.conf

if ([ ! -f ${BBLAYERS_CONF} ]);then
cat << eom
    Warning: Files ${BBLAYERS_CONF} not found.
    Make sure that the scritp issued at a correct location.
eom
    ${EXIT} 2
fi

BB_CL_CONF_DONE=conf/bb_cl_rt_conf.done
if [ -f ${BB_CL_CONF_DONE} ];then
cat << eom
    Note: Already issued.
    Nothing to be done.
eom
    ${EXIT} 0
fi

sed -i '$aBBLAYERS += " \\\n\t${BSPDIR}/sources/meta-compulab-rt \\\n"' ${BBLAYERS_CONF}
cat << eom
    Note: Files ${BBLAYERS_CONF} updated successfully.
eom

cat << eom > ${BB_CL_CONF_DONE}
$(date)
eom

${EXIT} 0
